/* Auto-generated by genmsg_cpp from file /home/cwkj/PX4-Autopilot/msg/magnetometer_bias_estimate.msg */


#pragma once


#include <uORB/uORB.h>


#ifndef __cplusplus

#endif


#ifdef __cplusplus
struct __EXPORT magnetometer_bias_estimate_s {
#else
struct magnetometer_bias_estimate_s {
#endif
	uint64_t timestamp;
	float bias_x[4];
	float bias_y[4];
	float bias_z[4];
	bool valid[4];
	bool stable[4];


#ifdef __cplusplus

#endif
};
