/* Auto-generated by genmsg_cpp from file /home/cwkj/PX4-Autopilot/msg/sensor_preflight_mag.msg */


#pragma once


#include <uORB/uORB.h>


#ifndef __cplusplus

#endif


#ifdef __cplusplus
struct __EXPORT sensor_preflight_mag_s {
#else
struct sensor_preflight_mag_s {
#endif
	uint64_t timestamp;
	float mag_inconsistency_angle;
	uint8_t _padding0[4]; // required for logger


#ifdef __cplusplus

#endif
};
