/* Auto-generated by genmsg_cpp from file /home/cwkj/PX4-Autopilot/msg/sensor_baro.msg */


#pragma once


#include <uORB/uORB.h>


#ifndef __cplusplus
#define SENSOR_BARO_ORB_QUEUE_LENGTH 4

#endif


#ifdef __cplusplus
struct __EXPORT sensor_baro_s {
#else
struct sensor_baro_s {
#endif
	uint64_t timestamp;
	uint64_t timestamp_sample;
	uint32_t device_id;
	float pressure;
	float temperature;
	uint32_t error_count;


#ifdef __cplusplus
	static constexpr uint8_t ORB_QUEUE_LENGTH = 4;

#endif
};
