/* Auto-generated by genmsg_cpp from file /home/cwkj/PX4-Autopilot/msg/sensor_mag.msg */


#pragma once


#include <uORB/uORB.h>

#ifdef __cplusplus
struct __EXPORT sensor_opticalflow_s {
#else
struct sensor_opticalflow_s {
#endif

	uint64_t timestamp;               // time since system start (microseconds)
	uint64_t timestamp_sample;

	uint32_t device_id;               // unique device ID for the sensor that does not change between power cycles

	float pixel_flow[2];          // (radians) optical flow in radians where a positive value is produced by a RH rotation about the body axis

	float delta_angle[3];         // (radians) accumulated gyro radians where a positive value is produced by a RH rotation about the body axis. Set to NaN if flow sensor does not have 3-axis gyro data.
	bool delta_angle_available;

	float distance_m;             // (meters) Distance to the center of the flow field
	bool distance_available;

	uint32_t integration_timespan_us; // (microseconds) accumulation timespan in microseconds

	uint8_t quality;                  // quality, 0: bad quality, 255: maximum quality

	uint32_t error_count;

	float max_flow_rate;          // (radians/s) Magnitude of maximum angular which the optical flow sensor can measure reliably

	float min_ground_distance;    // (meters) Minimum distance from ground at which the optical flow sensor operates reliably
	float max_ground_distance;    // (meters) Maximum distance from ground at which the optical flow sensor operates reliably

	uint8_t mode;

#ifdef __cplusplus
	static constexpr uint8_t MODE_UNKNOWN        = 0;
	static constexpr uint8_t MODE_BRIGHT         = 0;
	static constexpr uint8_t MODE_LOWLIGHT       = 0;
	static constexpr uint8_t MODE_SUPER_LOWLIGHT = 0;
	
#endif
};
