/* Auto-generated by genmsg_cpp from file /home/cwkj/PX4-Autopilot/msg/sensor_gyro_fft.msg */


#pragma once


#include <uORB/uORB.h>


#ifndef __cplusplus

#endif


#ifdef __cplusplus
struct __EXPORT sensor_gyro_fft_s {
#else
struct sensor_gyro_fft_s {
#endif
	uint64_t timestamp;
	uint64_t timestamp_sample;
	uint32_t device_id;
	float sensor_sample_rate_hz;
	float resolution_hz;
	float peak_frequencies_x[3];
	float peak_frequencies_y[3];
	float peak_frequencies_z[3];
	float peak_snr_x[3];
	float peak_snr_y[3];
	float peak_snr_z[3];
	uint8_t _padding0[4]; // required for logger


#ifdef __cplusplus

#endif
};

