/* Auto-generated by genmsg_cpp from file /home/cwkj/PX4-Autopilot/msg/sensor_gyro_fifo.msg */


#pragma once


#include <uORB/uORB.h>


#ifndef __cplusplus
#define SENSOR_GYRO_FIFO_ORB_QUEUE_LENGTH 4

#endif


#ifdef __cplusplus
struct __EXPORT sensor_gyro_fifo_s {
#else
struct sensor_gyro_fifo_s {
#endif
	uint64_t timestamp;
	uint64_t timestamp_sample;
	uint32_t device_id;
	float dt;
	float scale;
	int16_t x[32];
	int16_t y[32];
	int16_t z[32];
	uint8_t samples;
	uint8_t _padding0[3]; // required for logger


#ifdef __cplusplus
	static constexpr uint8_t ORB_QUEUE_LENGTH = 4;

#endif
};
