/* Auto-generated by genmsg_cpp from file /home/cwkj/PX4-Autopilot/msg/sensor_mag.msg */


#pragma once


#include <uORB/uORB.h>


#ifndef __cplusplus
#define SENSOR_MAG_ORB_QUEUE_LENGTH 4

#endif


#ifdef __cplusplus
struct __EXPORT sensor_mag_s {
#else
struct sensor_mag_s {
#endif
	uint64_t timestamp;
	uint64_t timestamp_sample;
	uint32_t device_id;
	float x;
	float y;
	float z;
	float temperature;
	uint32_t error_count;


#ifdef __cplusplus
	static constexpr uint8_t ORB_QUEUE_LENGTH = 4;

#endif
};

