/* Auto-generated by genmsg_cpp from file /home/cwkj/PX4-Autopilot/msg/vehicle_acceleration.msg */


#pragma once


#include <uORB/uORB.h>


#ifndef __cplusplus

#endif


#ifdef __cplusplus
struct __EXPORT vehicle_acceleration_s {
#else
struct vehicle_acceleration_s {
#endif
	uint64_t timestamp;
	uint64_t timestamp_sample;
	float xyz[3];
	uint8_t _padding0[4]; // required for logger


#ifdef __cplusplus

#endif
};
