/* Auto-generated by genmsg_cpp from file /home/cwkj/PX4-Autopilot/msg/vehicle_imu_status.msg */


#pragma once


#include <uORB/uORB.h>


#ifndef __cplusplus

#endif


#ifdef __cplusplus
struct __EXPORT vehicle_imu_status_s {
#else
struct vehicle_imu_status_s {
#endif
	uint64_t timestamp;
	uint32_t accel_device_id;
	uint32_t gyro_device_id;
	uint32_t accel_clipping[3];
	uint32_t accel_error_count;
	uint32_t gyro_error_count;
	float accel_rate_hz;
	float gyro_rate_hz;
	float accel_raw_rate_hz;
	float gyro_raw_rate_hz;
	float accel_vibration_metric;
	float gyro_vibration_metric;
	float delta_angle_coning_metric;
	float mean_accel[3];
	float mean_gyro[3];
	float var_accel[3];
	float var_gyro[3];
	float temperature_accel;
	float temperature_gyro;


#ifdef __cplusplus

#endif
};
